blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://github.com/gekal-study-tools/intellij-platform-plugin-flowable-editor#readme
    about: Check the README file in the first place.
  - name: Flowable BPMN documentation
    url: https://www.flowable.com/open-source/docs/bpmn/ch07b-BPMN-Constructs
    about: Reference for the BPMN constructs Flowable supports.
  - name: Getting Help
    url: https://plugins.jetbrains.com/docs/intellij/getting-help.html
    about: Check if you search for a help in plugin development.
